image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      echo 'export PATH=~/.local/bin:"$PATH"' >> ~/.bashrc &&
      source ~/.bashrc &&
      cd /workspace &&
      pip3 install --user -U west &&
      west init -l zephyr &&
      west update &&
      pip3 install --user -r /workspace/zephyr/scripts/requirements.txt
    command: >
      export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb &&
      export GNUARMEMB_TOOLCHAIN_PATH="/usr" &&
      source /workspace/zephyr/zephyr-env.sh
